export const LOGIN_WAS_CHANGED = "LOGIN_WAS_CHANGED";
export const PASSWORD_WAS_CHANGED = "PASSWORD_WAS_CHANGED";
export const CONFIRM_PASSWORD_WAS_CHANGED = "CONFIRM_PASSWORD_WAS_CHANGED";
export const EMAIL_WAS_CHANGED = "EMAIL_WAS_CHANGED";

export const LOGIN_NOT_UNIQUE = "LOGIN_NOT_UNIQUE";
export const EMAIL_NOT_UNIQUE = "EMAIL_NOT_UNIQUE";
export const CONFIRM_PASSWORD_FAILED = "CONFIRM_PASSWORD_FAILED";

export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SUCCESSFULLY_REGISTERED = "USER_SUCCESSFULLY_REGISTERED";