export const INPUT_LOGIN_WAS_CHANGED = "INPUT_LOGIN_WAS_CHANGED";
export const INPUT_PASSWORD_WAS_CHANGED = "INPUT_PASSWORD_WAS_CHANGED";
export const USER_SUCCESSFULLY_LOGGED = "USER_SUCCESSFULLY_LOGGED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_SIGN_IN = "USER_SIGN_IN";